apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken
  labels:
    app: kraken
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kraken
  template:
    metadata:
      labels:
        app: kraken
        tier: backend
    spec:
      containers:
      - image: asia.gcr.io/soy-channel-216515/kraken:0.1.3
        name: kraken
        env:
        - name: KRAKEN_ASSET_PAIRS
          value: BTCUSD:ETHUSD:ETHBTC
        - name: KRAKEN_FETCH_MODE
          value: trade
        - name: SAMMY_TRANSLATOR
          value: http://collector:8080

