apiVersion: v1
kind: Pod
metadata:
  name: migration-test-pod
  labels:
    app: migration-test-pod
    tier: testing
spec:
  containers:
  - image: asia.gcr.io/soy-channel-216515/trade-history-migrate:0.1.1
    name: trade-history-migrate
    env:
    - name: DATABASE_URL
      value: postgres://postgres:collector@postgres/sammy_trade_history
