apiVersion: v1
kind: Service
metadata:
  name: sammy-service
  labels:
    app: webserver
    tier: frontend
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: webserver
